--1a
CREATE VIEW ygezuMAJOR_CUSTOMER AS
(SELECT cust_id, first_name, last_name, balance, credit_limit, rep_id
FROM Customer
WHERE credit_limit <= 500);

--1b
SELECT cust_id, first_name, last_name
FROM ygezuMAJOR_CUSTOMER
WHERE (balance > credit_limit);

--1c
DROP VIEW ygezuMAJOR_CUSTOMER;

--2a
CREATE VIEW ygezu_ITEM_INVOICE AS
(SELECT ITEM.ITEM_ID, ITEM.DESCRIPTION, ITEM.PRICE, INVOICE_LINE.INVOICE_NUM, INVOICES.INVOICE_DATE, INVOICE_LINE.QUANTITY, INVOICE_LINE.QUOTED_PRICE
FROM ITEM, INVOICE_LINE, INVOICES
WHERE (INVOICE_LINE.INVOICE_NUM = INVOICES.INVOICE_NUM) AND (ITEM.ITEM_ID = INVOICE_LINE.ITEM_ID)
);

--2b
SELECT item_id, description, invoice_num, quoted_price
FROM ygezu_ITEM_INVOICE
WHERE quoted_price > 100;

--2c
DROP VIEW ygezu_ITEM_INVOICE;



--3a
CREATE VIEW ygezu_INVOICE_TOTAL AS
SELECT
    il.invoice_num,
    SUM(il.quantity * il.quoted_price) AS TOTAL_AMOUNT
FROM
    Invoice_Line il
GROUP BY
    il.invoice_num;

--3b 
SELECT invoice_num, TOTAL_AMOUNT
FROM ygezu_INVOICE_TOTAL
WHERE TOTAL_AMOUNT > 250;

--3c
DROP VIEW ygezu_INVOICE_TOTAL;

--4
CREATE INDEX ygezu_ITEM_INDEX1 ON INVOICE_LINE (ITEM_ID);

--5
CREATE INDEX ygezu_ITEM_INDEX2 ON ITEM (CATEGORY);

--6
CREATE INDEX ygezu_ITEM_INDEX3 ON ITEM (CATEGORY, LOCATION);

--7
CREATE INDEX ygezu_ITEM_INDEX4 ON ITEM (CATEGORY DESC, LOCATION);

--8
DROP INDEX ygezu_ITEM_INDEX1 ON INVOICE_LINE;
DROP INDEX ygezu_ITEM_INDEX2 ON ITEM;
DROP INDEX ygezu_ITEM_INDEX3 ON ITEM;
DROP INDEX ygezu_ITEM_INDEX4 ON ITEM;

--9
-- Adding FOREIGN KEY constraint
ALTER TABLE INVOICE_LINE
ADD CONSTRAINT FK_INVOICE_NUM
FOREIGN KEY (INVOICE_NUM) REFERENCES INVOICES(INVOICE_NUM);

-- Dropping the FOREIGN KEY constraint
ALTER TABLE INVOICE_LINE
DROP CONSTRAINT FK_INVOICE_NUM;

--10
-- Adding CHECK constraint for CREDIT_LIMIT
ALTER TABLE CUSTOMER
ADD CONSTRAINT CK_CREDIT_LIMIT
CHECK (CREDIT_LIMIT IN (250, 500, 750, 1000));

-- Dropping the CHECK constraint for CREDIT_LIMIT
ALTER TABLE CUSTOMER
DROP CONSTRAINT CK_CREDIT_LIMIT;









