-- Utility (Ignore)
DROP TABLE LSCHULZNONCAT
SELECT * FROM LSCHULZNONCAT

-- #1
CREATE TABLE LSCHULZNONCAT (
ITEM_ID CHAR(4) PRIMARY KEY, 
[DESCRIPTION] CHAR(30) NULL,
ON_HAND DECIMAL(4, 0) NULL,
CATEGORY CHAR(3) NULL,
PRICE DECIMAL(6, 2) NULL
)

-- #2
INSERT INTO LSCHULZNONCAT SELECT ITEM_ID, [DESCRIPTION], ON_HAND, CATEGORY, PRICE FROM ITEM WHERE CATEGORY != 'cat'

-- #3
UPDATE LSCHULZNONCAT SET [DESCRIPTION] = 'Dog Toy Gift Bananza' WHERE ITEM_ID = 'DT12'

-- #4
UPDATE LSCHULZNONCAT SET PRICE = PRICE * 1.05 WHERE CATEGORY = 'BRD'

-- #5
INSERT INTO LSCHULZNONCAT VALUES('FF17', 'Premium Fish Food', 10, 'CSH', 11.95)

-- #6
DELETE LSCHULZNONCAT WHERE CATEGORY = 'HOR'

-- #7 
UPDATE LSCHULZNONCAT SET CATEGORY = NULL WHERE ITEM_ID = 'UF39'

-- #8
ALTER TABLE LSCHULZNONCAT ADD ON_HAND_VALUE DECIMAL(7, 2)
UPDATE LSCHULZNONCAT SET ON_HAND_VALUE = PRICE * ON_HAND

-- #9
ALTER TABLE LSCHULZNONCAT ALTER COLUMN [DESCRIPTION] CHAR(40) NULL

