--1 
Create table ygezuNONCAT
 ( 
Item_ID CHAR(4) Primary key NOT NULL,
 Description CHAR(30), 
On_Hand DECIMAL(4,0), 
Category CHAR(3), 
Price DECIMAL(6,2)
);
--2
INSERT INTO ygezuNONCAT (ITEM_ID, DESCRIPTION, ON_HAND, CATEGORY, PRICE)
SELECT ITEM_ID, DESCRIPTION, ON_HAND, CATEGORY, PRICE
FROM ITEM
WHERE CATEGORY != 'CAT';

--3
UPDATE ygezuNONCAT
SET DESCRIPTION = 'Dog Toy Gift Bonanza'
WHERE ITEM_ID = 'DT12';

--4
UPDATE ygezuNONCAT
SET PRICE = (PRICE * 1.05)
WHERE CATEGORY='BRD';

--5
INSERT INTO ygezuNONCAT
VALUES('FF17', 'Premium Fish Food', 10, 'FSH', 11.95);

--6
DELETE FROM ygezuNONCAT
WHERE CATEGORY = 'HOR';

--7
UPDATE ygezuNONCAT
SET CATEGORY = NULL
WHERE ITEM_ID = 'UF39';

--8
ALTER TABLE ygezuNONCAT
ADD ON_HAND_VALUE DECIMAL(7, 2);

UPDATE ygezuNONCAT
SET ON_HAND_VALUE = (ON_HAND * PRICE);

--9
Alter TABLE ygezuNONCAT
Alter column DESCRIPTION CHAR(40);


